public class connectaddressandcontact {
    /* public static void matchContactandAddress()
    {
        
        list<contact> cont=new list<contact>();
        list<address__c> address=new list<Address__c>();
        
        address.add(add);
        contact c1=new contact();
        address__c a1=new address__c();
        for(contact c2:[select lastname,id from contact where lastname=:address.name])
        { 
            system.debug(c1.lastname);
        }
        
       
    }*/

}